### ISSUE TITLE
Join error

### ISSUE THREAD

**Issue by download042** [Rexcantor/MultiLanguagePlugin#16]
Hi.
I got this error, on join.
Any ideas? :S 

---------------------------------

[18:28:38] [Server thread/INFO]: FabricSoftener[/91.82.200.65:14888] logged in with entity id 250 at ([world]9.41611193867107, 62.87746548694633, -33.64916193926855)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:28:38] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
[18:28:38] [Server thread/WARN]: 	at java.lang.String.charAt(String.java:658)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.e.a.c(LanguageUtils.java:61)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.a(NM_1_8_R3.java:205)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.handle(NM_1_8_R3.java:90)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.nms.NM_1_8_R3.b_(NM_1_8_R3.java:401)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.b(LanguagePlayer.java:44)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer.a(LanguagePlayer.java:40)
[18:28:38] [Server thread/WARN]: 	at com.cloutteam.rex.multilanguage.LanguagePlayer$1.run(LanguagePlayer.java:24)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:29:14] [Server thread/INFO]: FabricSoftener lost connection: Internal Exception: java.io.IOException: Error while read(...): A kapcsolatot bontotta a távoli fél

------------------------

**Comment by Rexcantor** [comment]
No idea, but I'll take a look

**Comment by download042** [comment]
No more join errors in console :D wtf
Just a kick msg... : 
http://prntscr.com/frmvq2

If the plugin loading, kick everybody on the server, from all worlds.

Still kicking, after unloaded the following plugins:
TitleManager,HolographicDisplays,HolographicScoreboard,floAuction,AAC,AWD,AdvancedLogin,Animatronics,SkyBlockOres,ImageOnMap,HeadDrops,MiniaturePets,NickNameFixer,AntiCommandTab,ChestCommands,Lift,Essentials, EssentialsChat, EssentialsSpawn,PlaceholderAPI,PrisonMines,ProtocolLib,RedstoneClockPreventer2,SendOnShutdown-Bukkit,SilkSpawners,SkinsRestorer,TreasureChest,VariableTriggers,CleanRoomGenerator,WorldEdit,YouTubeBridge,NoNetherPortals,NoFallDamage,Clearlag,ColorMenu,CombatLog,DeathMessages,EnderDragonRespawner,GUISeller,InstantRespawn,ItemCases

Not unloaded plugins:  http://prntscr.com/frn6oy

**Comment by Rexcantor** [comment]
Are you using a scoreboard? If so, did you add any MLP placeholder to the scoreboard?

**Comment by download042** [comment]
Nope ^^

**Comment by Rexcantor** [comment]
Did you add any MLP placeholder at all?

**Comment by download042** [comment]
I do not know about it.
Are you talking about these?
https://www.spigotmc.org/wiki/multilanguageplugin/#placeholders

**Comment by Rexcantor** [comment]
Yeah. But if you don't know, then you probably didn't add.

**Comment by download042** [comment]
I have not used any of them yet.

**Comment by download042** [comment]
Only [lang] and [/lang].. 
We maked 3 servers, with this plugin, with 4 different languages.
Until now, there was no problem

**Comment by download042** [comment]
Btw. very nice plugin. :) One of the best.

**Comment by download042** [comment]
All language files are deleted.. :DD
Still kick. This is funny.

**Comment by download042** [comment]
I can give you server IP if you want. :S

**Comment by Rexcantor** [comment]
Lol, [lang] [/lang] is a placeholder :P
If you're using it on a scoreboard, please make sure you aren't missing the code in the language file.

Btw, I fixed the first bug.

**Comment by download042** [comment]
We used FeatherBoard, two weeks ago. But already uninstalled.. No scoreboard plugin installed. :/

**Comment by download042** [comment]
We uninstalled, because after the lang change, everything went mad
Just like this: https://prnt.sc/fp4km5
After turn off and turn on the scoreboard, it was better, but it was not perfect either, so we uninstalled Featherboard.

**Comment by Rexcantor** [comment]
Can you add me on Skype or Discord then? (I prefer Discord) The usernames are on the plugin page

**Comment by download042** [comment]
Yup, but i can't speak, lol.
Just chat :S

**Comment by Rexcantor** [comment]
## For everyone having the same problem:
The error on the first post was fixed and will be released on 0.3.3.

About the second problem (the kick one), you should delete your `data/scoreboard.dat` file inside your world folder if you don't see any objectives listed with `/scoreboard objectives list`. Just backup it first, so you can revert if it wasn't the problem.
