### ISSUE TITLE
Server change error

### ISSUE THREAD

**Issue by download042** [Rexcantor/MultiLanguagePlugin#40]
**MLP version: Triton-v1.0.0-BETA-4
**Minecraft version: 1.11.2
**Server software: bungeecord
**Using BungeeCord: yes, waterfallmc.

**Issue type:** Bug report  
#### Description:
At server change i received this error in the bungee console.

### Error logs (in case it's a bug report):
[13:04:22] [Netty Worker IO Thread #13/WARN]: Error dispatching event ServerConnectedEvent(player=FabricSoftener, server=net.md_5.bungee.ServerConnection@671a28a0) to listener com.rexcantor64.triton.bridge.BungeeBridgeManager@16949dfa
java.lang.NullPointerException: null
	at com.rexcantor64.triton.bridge.BungeeBridgeManager.onPlayerJoin(BungeeBridgeManager.java:88) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:411) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:209) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:72) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[minecraft.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:abae6c9:229]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Rexcantor** [comment]
Fixed
