### ISSUE TITLE
Error on 1.9 R2

### ISSUE THREAD

**Issue by Rexcantor** [Rexcantor/MultiLanguagePlugin#8]
Thanks, @monnoliv for reporting this bug!

### Stack trace:

`[18:24:18] [Server thread/WARN]: java.lang.ClassCastException: java.util.concurrent.locks.ReentrantReadWriteLock cannot be cast to java.util.Map
[18:24:18] [Server thread/WARN]: at com.cloutteam.rex.multilanguage.nms.NM_1_9_R2.a(NM_1_9_R2.java:200)
[18:24:18] [Server thread/WARN]: at com.cloutteam.rex.multilanguage.nms.NM_1_9_R2.sendPacket(NM_1_9_R2.java:81)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerConnection.sendPacket(PlayerConnection.java:1095)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.EntityTracker.a(EntityTracker.java:257)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerChunk.sendChunk(PlayerChunk.java:148)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerChunk.a(PlayerChunk.java:66)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:279)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:291)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerList.onPlayerJoin(PlayerList.java:367)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.PlayerList.a(PlayerList.java:159)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.LoginListener.b(LoginListener.java:144)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.LoginListener.c(LoginListener.java:54)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[18:24:18] [Server thread/WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[18:24:18] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)`

There is still no information about when/how it occurs.

**Comment by Rexcantor** [comment]
Fixed.
